<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FaultTree" nsURI="http://www.aadl.info/FaultTree" nsPrefix="FaultTree">
  <eClassifiers xsi:type="ecore:EClass" name="FaultTree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subEvents" upperBound="-1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subEventLogic" eType="#//LogicOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="Basic"/>
    <eLiterals name="External" value="1"/>
    <eLiterals name="Undeveloped" value="2"/>
    <eLiterals name="Intermediate" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOperation">
    <eLiterals name="Noop"/>
    <eLiterals name="Or" value="1"/>
    <eLiterals name="And" value="2"/>
    <eLiterals name="Xor" value="3"/>
    <eLiterals name="PriorityAnd" value="4"/>
    <eLiterals name="kOf" value="5"/>
    <eLiterals name="kOrmore" value="6"/>
    <eLiterals name="kOrless" value="7"/>
  </eClassifiers>
</ecore:EPackage>
