<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FaultTree" nsURI="http://www.aadl.info/FaultTree" nsPrefix="FaultTree">
  <eClassifiers xsi:type="ecore:EClass" name="FaultTree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultTreeType" eType="#//FaultTreeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceRoot" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eOperations name="getProbability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subEvents" upperBound="-1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignedProbability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computedProbability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedInstanceObject"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedErrorType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subEventLogic" eType="#//LogicOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedEMV2Object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="Basic"/>
    <eLiterals name="External" value="1"/>
    <eLiterals name="Undeveloped" value="2"/>
    <eLiterals name="Intermediate" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOperation">
    <eLiterals name="Or"/>
    <eLiterals name="And" value="1"/>
    <eLiterals name="Xor" value="2"/>
    <eLiterals name="PriorityAnd" value="3"/>
    <eLiterals name="kOf" value="4"/>
    <eLiterals name="kOrmore" value="5"/>
    <eLiterals name="kOrless" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaultTreeType">
    <eLiterals name="FaultTree"/>
    <eLiterals name="FaultTrace" value="1"/>
    <eLiterals name="CompositeParts" value="2"/>
    <eLiterals name="MinimalCutSet" value="3"/>
  </eClassifiers>
</ecore:EPackage>
