package org.osate.ge.graphics.internal;

public enum FeatureType {
	ABSTRACT,
	EVENT_PORT,
	DATA_PORT,
	EVENT_DATA_PORT,
	SUBPROGRAM_ACCESS,
	SUBPROGRAM_GROUP_ACCESS,
	DATA_ACCESS,
	BUS_ACCESS,
	FEATURE_GROUP,
	PORT_PROXY,
	EVENT_SOURCE,
	EVENT_DATA_SOURCE,
	SUBPROGRAM_PROXY
}
