/**
 * Copyright (c) 2004-2022 Carnegie Mellon University and others. (see Contributors file).
 * All Rights Reserved.
 * 
 * NO WARRANTY. ALL MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY
 * KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
 * OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
 * MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 * 
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Created, in part, with funding and support from the United States Government. (see Acknowledgments file).
 * 
 * This program includes and/or can make use of certain third party source code, object code, documentation and other
 * files ("Third Party Software"). The Third Party Software that is used by this program is dependent upon your system
 * configuration. By using this program, You agree to comply with any and all relevant Third Party Software terms and
 * conditions contained in any such Third Party Software or separate license file distributed with such Third Party
 * Software. The parties who own the Third Party Software ("Third Party Licensors") are intended third party benefici-
 * aries to this license with respect to the terms applicable to their Third Party Software. Third Party Software li-
 * censes only apply to the Third Party Software and not any other portion of this program or this program as a whole.
 */
package org.osate.reqtrace.tests;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Functions.Function0;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.Pair;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.osate.aadl2.AadlPackage;
import org.osate.aadl2.Classifier;
import org.osate.testsupport.BIRTTest;

@RunWith(XtextRunner.class)
@InjectWith(AlisaUiInjectorProvider.class)
@SuppressWarnings("all")
public class RequirementsReportTest extends BIRTTest {
  private static final String REQUIREMENTS_RPTDESIGN_URL = "platform:/plugin/org.osate.reqtrace/requirements.rptdesign";

  @Test
  public void testRequirementsReport() {
    final String pkg1FileName = "pkg1.aadl";
    final String systemRequirements1FileName = "systemRequirements1.reqspec";
    final String document1FileName = "document1.reqdoc";
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package pkg1");
    _builder.newLine();
    _builder.append("public");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("system sys1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("end sys1;");
    _builder.newLine();
    _builder.append("end pkg1;");
    _builder.newLine();
    Pair<String, String> _mappedTo = Pair.<String, String>of(pkg1FileName, _builder.toString());
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("system requirements systemRequirements1 for pkg1::sys1 [");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("requirement req1 [");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("]");
    _builder_1.newLine();
    _builder_1.append("]");
    _builder_1.newLine();
    Pair<String, String> _mappedTo_1 = Pair.<String, String>of(systemRequirements1FileName, _builder_1.toString());
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append("document document1 [");
    _builder_2.newLine();
    _builder_2.append("\t");
    _builder_2.append("requirement req2 [");
    _builder_2.newLine();
    _builder_2.append("\t");
    _builder_2.append("]");
    _builder_2.newLine();
    _builder_2.append("]");
    _builder_2.newLine();
    Pair<String, String> _mappedTo_2 = Pair.<String, String>of(document1FileName, _builder_2.toString());
    this.createFiles(_mappedTo, _mappedTo_1, _mappedTo_2);
    this.suppressSerialization();
    EObject _head = IterableExtensions.<EObject>head(this.testFile(pkg1FileName).getResource().getContents());
    Classifier _head_1 = IterableExtensions.<Classifier>head(((AadlPackage) _head).getPublicSection().getOwnedClassifiers());
    Pair<String, Classifier> _mappedTo_3 = Pair.<String, Classifier>of("selectedObject", _head_1);
    Pair<String, String> _mappedTo_4 = Pair.<String, String>of("selectionType", "Classifier");
    this.assertReport(RequirementsReportTest.REQUIREMENTS_RPTDESIGN_URL, this.expectedClassifier, CollectionLiterals.<String, Object>newHashMap(_mappedTo_3, _mappedTo_4));
    String _projectName = this.getProjectName();
    Pair<String, String> _mappedTo_5 = Pair.<String, String>of("ProjectName", _projectName);
    Pair<String, String> _mappedTo_6 = Pair.<String, String>of("Directories", "");
    Pair<String, String> _mappedTo_7 = Pair.<String, String>of("FileName", systemRequirements1FileName);
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append("/");
    String _projectName_1 = this.getProjectName();
    _builder_3.append(_projectName_1);
    _builder_3.append("/");
    _builder_3.append(systemRequirements1FileName);
    Pair<String, String> _mappedTo_8 = Pair.<String, String>of("selectedObject", _builder_3.toString());
    Pair<String, String> _mappedTo_9 = Pair.<String, String>of("selectionType", "reqspec");
    this.assertReport(RequirementsReportTest.REQUIREMENTS_RPTDESIGN_URL, this.expectedReqspec, CollectionLiterals.<String, String>newHashMap(_mappedTo_5, _mappedTo_6, _mappedTo_7, _mappedTo_8, _mappedTo_9));
    String _projectName_2 = this.getProjectName();
    Pair<String, String> _mappedTo_10 = Pair.<String, String>of("ProjectName", _projectName_2);
    Pair<String, String> _mappedTo_11 = Pair.<String, String>of("Directories", "");
    Pair<String, String> _mappedTo_12 = Pair.<String, String>of("FileName", document1FileName);
    StringConcatenation _builder_4 = new StringConcatenation();
    _builder_4.append("/");
    String _projectName_3 = this.getProjectName();
    _builder_4.append(_projectName_3);
    _builder_4.append("/");
    _builder_4.append(document1FileName);
    Pair<String, String> _mappedTo_13 = Pair.<String, String>of("selectedObject", _builder_4.toString());
    Pair<String, String> _mappedTo_14 = Pair.<String, String>of("selectionType", "reqdoc");
    this.assertReport(RequirementsReportTest.REQUIREMENTS_RPTDESIGN_URL, this.expectedReqdoc, CollectionLiterals.<String, String>newHashMap(_mappedTo_10, _mappedTo_11, _mappedTo_12, _mappedTo_13, _mappedTo_14));
  }

  private final String expectedClassifier = new Function0<String>() {
    @Override
    public String apply() {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">");
      _builder.newLine();
      _builder.append("<html>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("<head>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<style type=\"text/css\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_13 { height: 0.292in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_8 { border-bottom: medium solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_9 { font-weight: bold; font-size: 12pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_6 { width: 7.927in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_7 { margin-top: auto; border: medium solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_0 { font-family: serif; font-style: normal; font-variant: normal; font-weight: normal; font-size: 10pt; color: black; text-indent: 0em; letter-spacing: normal; word-spacing: normal; text-transform: none; white-space: normal; line-height: normal;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_10 { border-top: 1px solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_12 { font-style: italic;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_11 { height: 0.594in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_4 { font-weight: bold; font-size: 9pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_5 { font-style: italic; font-size: 9pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_2 { font-size: 14pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_3 { width: 7.931in;}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</style>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<script type=\"text/javascript\">");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.append("//<![CDATA[");
      _builder.newLine();
      _builder.append("\t\t\t   ");
      _builder.append("function redirect(target, url){");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("if (target ==\'_blank\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("open(url);");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_top\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("window.top.location.href=url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_parent\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("location.href=url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_self\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("location.href =url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else{");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("open(url);");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t      ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.append("//]]>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</script>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</head>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<body class=\"style_0\" style=\" margin:0px;\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<table cellpadding=\"0\" style=\"empty-cells: show; border-collapse:collapse; width:8in; overflow: hidden; table-layout:fixed;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td></td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td valign=\"top\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<div class=\"style_2\" id=\"\" style=\" text-align:center;\">System Requirements Report</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<table class=\"style_6\" style=\"border-collapse: collapse; empty-cells: show; width: 7.927in; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col style=\" width: 0.865in;\"></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col style=\" width: 7.062in;\"></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">Classifier:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">pkg1::sys1</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<table class=\"style_7\" style=\"border-collapse: collapse; empty-cells: show; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"__bookmark_2\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_8\" valign=\"top\" align=\"center\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<th style=\" overflow:hidden;font-weight: normal; border-bottom: medium solid black;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_9\" id=\"\">Requirements</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</th>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_10\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden; border-top: 1px solid black;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<table class=\"style_11\" style=\"border-collapse: collapse; empty-cells: show; height: 0.594in; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_12\">systemRequirements1.req1</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_13\" style=\" height: 0.292in;\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_13\" style=\" height: 0.292in;\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\"></td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<div style=\"overflow:hidden; height:0.5in\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<table style=\"border-collapse: collapse; empty-cells: show; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\" overflow:hidden;\"></div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\" text-align:right;\">1</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</body>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("</html>");
      return _builder.toString();
    }
  }.apply();

  private final String expectedReqspec = new Function0<String>() {
    @Override
    public String apply() {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">");
      _builder.newLine();
      _builder.append("<html>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("<head>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<style type=\"text/css\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_13 { height: 0.292in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_8 { border-bottom: medium solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_9 { font-weight: bold; font-size: 12pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_6 { width: 7.927in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_7 { margin-top: auto; border: medium solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_0 { font-family: serif; font-style: normal; font-variant: normal; font-weight: normal; font-size: 10pt; color: black; text-indent: 0em; letter-spacing: normal; word-spacing: normal; text-transform: none; white-space: normal; line-height: normal;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_10 { border-top: 1px solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_12 { font-style: italic;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_11 { height: 0.594in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_4 { font-weight: bold; font-size: 9pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_5 { font-style: italic; font-size: 9pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_2 { font-size: 14pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_3 { width: 7.931in;}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</style>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<script type=\"text/javascript\">");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.append("//<![CDATA[");
      _builder.newLine();
      _builder.append("\t\t\t   ");
      _builder.append("function redirect(target, url){");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("if (target ==\'_blank\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("open(url);");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_top\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("window.top.location.href=url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_parent\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("location.href=url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_self\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("location.href =url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else{");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("open(url);");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t      ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.append("//]]>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</script>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</head>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<body class=\"style_0\" style=\" margin:0px;\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<table cellpadding=\"0\" style=\"empty-cells: show; border-collapse:collapse; width:8in; overflow: hidden; table-layout:fixed;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td></td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td valign=\"top\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<div class=\"style_2\" id=\"\" style=\" text-align:center;\">System Requirements Report</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<table class=\"style_3\" style=\"border-collapse: collapse; empty-cells: show; width: 7.931in; overflow:hidden; table-layout:fixed;\" id=\"__bookmark_1\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col style=\" width: 0.556in;\"></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col style=\" width: 7.375in;\"></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">Project:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">RequirementsReportTest</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">Folder:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">File:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">systemRequirements1.reqspec</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<table class=\"style_7\" style=\"border-collapse: collapse; empty-cells: show; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"__bookmark_2\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_8\" valign=\"top\" align=\"center\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<th style=\" overflow:hidden;font-weight: normal; border-bottom: medium solid black;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_9\" id=\"\">Requirements</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</th>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_10\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden; border-top: 1px solid black;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<table class=\"style_11\" style=\"border-collapse: collapse; empty-cells: show; height: 0.594in; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_12\">systemRequirements1.req1</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_13\" style=\" height: 0.292in;\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_13\" style=\" height: 0.292in;\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\"></td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<div style=\"overflow:hidden; height:0.5in\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<table style=\"border-collapse: collapse; empty-cells: show; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\" overflow:hidden;\"></div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\" text-align:right;\">1</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</body>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("</html>");
      return _builder.toString();
    }
  }.apply();

  private final String expectedReqdoc = new Function0<String>() {
    @Override
    public String apply() {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">");
      _builder.newLine();
      _builder.append("<html>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("<head>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<style type=\"text/css\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_13 { height: 0.292in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_8 { border-bottom: medium solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_9 { font-weight: bold; font-size: 12pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_6 { width: 7.927in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_7 { margin-top: auto; border: medium solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_0 { font-family: serif; font-style: normal; font-variant: normal; font-weight: normal; font-size: 10pt; color: black; text-indent: 0em; letter-spacing: normal; word-spacing: normal; text-transform: none; white-space: normal; line-height: normal;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_10 { border-top: 1px solid black;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_12 { font-style: italic;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_11 { height: 0.594in;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_4 { font-weight: bold; font-size: 9pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_5 { font-style: italic; font-size: 9pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_2 { font-size: 14pt;}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append(".style_3 { width: 7.931in;}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</style>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<script type=\"text/javascript\">");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.append("//<![CDATA[");
      _builder.newLine();
      _builder.append("\t\t\t   ");
      _builder.append("function redirect(target, url){");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("if (target ==\'_blank\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("open(url);");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_top\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("window.top.location.href=url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_parent\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("location.href=url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else if (target == \'_self\'){");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("location.href =url;");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("else{");
      _builder.newLine();
      _builder.append("\t\t\t           ");
      _builder.append("open(url);");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t      ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.append("//]]>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</script>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</head>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<body class=\"style_0\" style=\" margin:0px;\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<table cellpadding=\"0\" style=\"empty-cells: show; border-collapse:collapse; width:8in; overflow: hidden; table-layout:fixed;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td></td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td valign=\"top\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<div class=\"style_2\" id=\"\" style=\" text-align:center;\">System Requirements Report</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<table class=\"style_3\" style=\"border-collapse: collapse; empty-cells: show; width: 7.931in; overflow:hidden; table-layout:fixed;\" id=\"__bookmark_1\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col style=\" width: 0.556in;\"></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col style=\" width: 7.375in;\"></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">Project:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">RequirementsReportTest</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">Folder:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_4\" id=\"\">File:</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_5\">document1.reqdoc</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<table class=\"style_7\" style=\"border-collapse: collapse; empty-cells: show; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"__bookmark_2\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_8\" valign=\"top\" align=\"center\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<th style=\" overflow:hidden;font-weight: normal; border-bottom: medium solid black;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_9\" id=\"\">Requirements</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</th>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_10\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden; border-top: 1px solid black;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<table class=\"style_11\" style=\"border-collapse: collapse; empty-cells: show; height: 0.594in; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div class=\"style_12\">document1.req2</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_13\" style=\" height: 0.292in;\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<tr class=\"style_13\" style=\" height: 0.292in;\" valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\"visibility:hidden\">&#xa0;</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\"></td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("<td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("<div style=\"overflow:hidden; height:0.5in\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("<table style=\"border-collapse: collapse; empty-cells: show; width: 100%; overflow:hidden; table-layout:fixed;\" id=\"\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<col></col>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("<tr valign=\"top\" align=\"left\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\" overflow:hidden;\"></div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("<td style=\" overflow:hidden;\">");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t\t");
      _builder.append("<div style=\" text-align:right;\">1</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("</div>");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("</td>");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("</tr>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</body>");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("</html>");
      return _builder.toString();
    }
  }.apply();
}
