var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. Introduction', 'Introduction.html',{'tt':'1. Introduction','sb':' '},],
		['2. What’s New', 'WhatsNew.html',{'tt':'2. What’s New','sb':' '},
			['2.1 What’s New in OSATE 1.2', 'WhatsNewinOSATE1.2.html',{'tt':'2.1 What’s New in OSATE 1.2','sb':' '},],
			['2.2 What’s New in OSATE 1.1', 'WhatsNewinOSATE1.1.html',{'tt':'2.2 What’s New in OSATE 1.1','sb':' '},],
			['2.3 What’s New in OSATE 1.0', 'WhatsNewinOSATE1.0.html',{'tt':'2.3 What’s New in OSATE 1.0','sb':' '},],
],
		['3. Download and Installation', 'DownloadandInstallation.html',{'tt':'3. Download and Installation','sb':' '},
			['3.1 Installation of OSATE Bund... ', 'InstallationofOSATEBundledwithEclipse.html',{'tt':'3.1 Installation of OSATE Bundled with Eclipse','sb':' '},],
			['3.2 Install into an existing E... ', 'InstallintoanexistingEclipseinstallation.html',{'tt':'3.2 Install into an existing Eclipse installation','sb':' '},],
			['3.3 Use the Eclipse Installati... ', 'UsetheEclipseInstallation.UpdateManager.html',{'tt':'3.3 Use the Eclipse Installation/Update Manager','sb':' '},],
			['3.4 Problems with the Installa... ', 'ProblemswiththeInstallation.html',{'tt':'3.4 Problems with the Installation','sb':' '},],
			['3.5 Updating Your Installation', 'UpdatingYourInstallation.html',{'tt':'3.5 Updating Your Installation','sb':' '},],
],
		['4. Use of the AADL Tool Enviro... ', 'UseoftheAADLToolEnvironment(OSATE).html',{'tt':'4. Use of the AADL Tool Environment (OSATE)','sb':' '},
			['4.1 Starting Up OSATE for the ... ', 'StartingUpOSATEfortheFirstTime.html',{'tt':'4.1 Starting Up OSATE for the First Time','sb':' '},],
			['4.2 Managing AADL Models with ... ', 'ManagingAADLModelswithEclipseProjects.html',{'tt':'4.2 Managing AADL Models with Eclipse Projects','sb':' '},],
			['4.3 Eclipse Projects and Team ... ', 'EclipseProjectsandTeamSupport.html',{'tt':'4.3 Eclipse Projects and Team Support','sb':' '},],
			['4.4 Creating and Editing AADL ... ', 'CreatingandEditingAADLModels.html',{'tt':'4.4 Creating and Editing AADL Models','sb':' '},],
			['4.5 Predeclared AADL Propertie... ', 'PredeclaredAADLProperties.html',{'tt':'4.5 Predeclared AADL Properties','sb':' '},],
			['4.6 Automatic Build with the A... ', 'AutomaticBuildwiththeAADLBuilder.html',{'tt':'4.6 Automatic Build with the AADL Builder','sb':' '},],
			['4.7 Importing AADL Models into... ', 'ImportingAADLModelsintoOSATE.html',{'tt':'4.7 Importing AADL Models into OSATE','sb':' '},],
			['4.8 Synchronizing Eclipse/OSAT... ', 'SynchronizingEclipse.OSATEwiththeFileSys.html',{'tt':'4.8 Synchronizing Eclipse/OSATE with the File System','sb':' '},],
],
		['5. The AADL Text Editor', 'TheAADLTextEditor.html',{'tt':'5. The AADL Text Editor','sb':' '},
			['5.1 Syntax/Semantics Checking ... ', 'Syntax.SemanticsCheckingofAADLText.html',{'tt':'5.1 Syntax/Semantics Checking of AADL Text','sb':' '},],
			['5.2 Code Completion', 'CodeCompletion.html',{'tt':'5.2 Code Completion','sb':' '},],
			['5.3 Text Hover', 'TextHover.html',{'tt':'5.3 Text Hover','sb':' '},],
			['5.4 Working With Textual AADL ... ', 'WorkingWithTextualAADLModels.html',{'tt':'5.4 Working With Textual AADL Models','sb':' '},],
			['5.5 Semantic Checking and Tran... ', 'SemanticCheckingandTranslationtoXML.html',{'tt':'5.5 Semantic Checking and Translation to XML','sb':' '},],
],
		['6. Generating Reports from the... ', 'GeneratingReportsfromtheProblemsView.html',{'tt':'6. Generating Reports from the “Problems” View','sb':' '},],
		['7. The AADL Object Editor', 'TheAADLObjectEditor.html',{'tt':'7. The AADL Object Editor','sb':' '},
			['7.1 Viewing AADL Object Models', 'ViewingAADLObjectModels.html',{'tt':'7.1 Viewing AADL Object Models','sb':' '},],
			['7.2 Navigating AADL Object Mod... ', 'NavigatingAADLObjectModels.html',{'tt':'7.2 Navigating AADL Object Models','sb':' '},],
			['7.3 Editing in the AADL Object... ', 'EditingintheAADLObjectEditor.html',{'tt':'7.3 Editing in the AADL Object Editor','sb':' '},],
			['7.4 Viewing the System Instanc... ', 'ViewingtheSystemInstanceHierarchyintheDe.html',{'tt':'7.4 Viewing the System Instance Hierarchy in the Declarative Model','sb':' '},],
			['7.5 Creating and Working with ... ', 'CreatingandWorkingwithAADLInstanceModels.html',{'tt':'7.5 Creating and Working with AADL Instance Models','sb':' '},],
			['7.6 Generating Textual AADL', 'GeneratingTextualAADL.html',{'tt':'7.6 Generating Textual AADL','sb':' '},],
			['7.7 The “AADL Property Values”... ', 'TheAADLPropertyValuesView.html',{'tt':'7.7 The “AADL Property Values” View','sb':' '},],
],
		['8. The AADL Graphical Editor', 'TheAADLGraphicalEditor.html',{'tt':'8. The AADL Graphical Editor','sb':' '},
			['8.1 From AADL Text to a Graphi... ', 'FromAADLTexttoaGraphicalAADLDiagram.html',{'tt':'8.1 From AADL Text to a Graphical AADL Diagram','sb':' '},],
			['8.2 Graphical Editing', 'GraphicalEditing.html',{'tt':'8.2 Graphical Editing','sb':' '},],
],
		['9. Analysis of Declarative AAD... ', 'AnalysisofDeclarativeAADLModelsandAADLIn.html',{'tt':'9. Analysis of Declarative AADL Models and AADL Instance Models','sb':' '},
			['9.1 Additional Semantic Checks', 'AdditionalSemanticChecks.html',{'tt':'9.1 Additional Semantic Checks','sb':' '},],
			['9.2 Architecture Analyses', 'ArchitectureAnalyses.html',{'tt':'9.2 Architecture Analyses','sb':' '},],
			['9.3 Security and Safety Level ... ', 'SecurityandSafetyLevelChecking.html',{'tt':'9.3 Security and Safety Level Checking','sb':' '},],
			['9.4 Flow Latency Analysis', 'FlowLatencyAnalysis.html',{'tt':'9.4 Flow Latency Analysis','sb':' '},],
			['9.5 MetaH Generation', 'MetaHGeneration.html',{'tt':'9.5 MetaH Generation','sb':' '},],
			['9.6 Thread–Processor Binding', 'ThreadProcessorBinding.html',{'tt':'9.6 Thread–Processor Binding','sb':' '},],
			['9.7 Do It Yourself', 'DoItYourself.html',{'tt':'9.7 Do It Yourself','sb':' '},],
],
		['10. Flow Latency Analysis', 'FlowLatencyAnalysis(2).html',{'tt':'10. Flow Latency Analysis','sb':' '},
			['10.1 Fully and Partially Speci... ', 'FullyandPartiallySpecifiedInstanceModels.html',{'tt':'10.1 Fully and Partially Specified Instance Models','sb':' '},],
			['10.2 End-To-End Flow Latency A... ', 'End-To-EndFlowLatencyAnalysisonInstanceM.html',{'tt':'10.2 End-To-End Flow Latency Analysis on Instance Models','sb':' '},],
			['10.3 End-To-End Flow Latency A... ', 'End-To-EndFlowLatencyAnalysisonDeclarati.html',{'tt':'10.3 End-To-End Flow Latency Analysis on Declarative Models','sb':' '},],
			['10.4 Flow Implementation Laten... ', 'FlowImplementationLatencyAnalysisonDecla.html',{'tt':'10.4 Flow Implementation Latency Analysis on Declarative Models','sb':' '},],
			['10.5 Example Models for Flow A... ', 'ExampleModelsforFlowAnalysis.html',{'tt':'10.5 Example Models for Flow Analysis','sb':' '},],
],
		['11. Example Models', 'ExampleModels.html',{'tt':'11. Example Models','sb':' '},
			['11.1 Securityexample.aadl', 'Securityexample.aadl.html',{'tt':'11.1 Securityexample.aadl','sb':' '},],
			['11.2 Safetyexample.aadl', 'Safetyexample.aadl.html',{'tt':'11.2 Safetyexample.aadl','sb':' '},],
			['11.3 Sunseekerdemo.aadl', 'Sunseekerdemo.aadl.html',{'tt':'11.3 Sunseekerdemo.aadl','sb':' '},],
			['11.4 Avionics_System.aadl', 'Avionics_System.aadl.html',{'tt':'11.4 Avionics_System.aadl','sb':' '},],
			['11.5 Display_System.aadl', 'Display_System.aadl.html',{'tt':'11.5 Display_System.aadl','sb':' '},],
			['11.6 Tripleredundant.aadl', 'Tripleredundant.aadl.html',{'tt':'11.6 Tripleredundant.aadl','sb':' '},],
			['11.7 Instancemodeexample.aadl', 'Instancemodeexample.aadl.html',{'tt':'11.7 Instancemodeexample.aadl','sb':' '},],
			['11.8 Flight Control System', 'FlightControlSystem.html',{'tt':'11.8 Flight Control System','sb':' '},],
			['11.9 Cruise_Control.aadl', 'Cruise_Control.aadl.html',{'tt':'11.9 Cruise_Control.aadl','sb':' '},],
			['11.10 CockpitDisplay.aadl', 'CockpitDisplay.aadl.html',{'tt':'11.10 CockpitDisplay.aadl','sb':' '},],
],
		['12. Problems and Errors', 'ProblemsandErrors.html',{'tt':'12. Problems and Errors','sb':' '},],
		['13. OSATE Implementation Backg... ', 'OSATEImplementationBackground.html',{'tt':'13. OSATE Implementation Background','sb':' '},],

]
];