source.. = src/,\
           src-gen/
bin.includes = META-INF/,\
               .,\
               model/generated/,\
               plugin.xml
bin.excludes = **/*.launch,\
               **/.gitignore
