package org.osate.ge.internal.diagram.runtime;

public enum DiagramElementField {
	ID,
	MANUAL,
	AUTO_CONTENTS_FILTER,
	COMPLETENESS,
	NAME,
	GRAPHICAL_CONFIGURATION,
	POSITION,
	SIZE,
	DOCK_AREA,
	BENDPOINTS,
	CONNECTION_PRIMARY_LABEL_POSITION,
	RELATIVE_REFERENCE
}