package org.osate.ge.internal.diagram.runtime;

public enum ModifiableField {
	MANUAL,
	CONTENT_FILTERS,
	COMPLETENESS,
	LABEL_NAME,
	USER_INTERFACE_NAME,
	GRAPHICAL_CONFIGURATION,
	POSITION,
	SIZE,
	DOCK_AREA,
	STYLE,
	BENDPOINTS,
	CONNECTION_PRIMARY_LABEL_POSITION,
	RELATIVE_REFERENCE,
	DIAGRAM_CONFIGURATION
}