/*
 * generated by Xtext
 */
package org.osate.assure;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AssureUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.osate.assure.ui.internal.AssureActivator.getInstance().getInjector("org.osate.assure.Assure");
	}
	
}
