var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. Reader’s Notes', 'ReadersNotes.html',{'tt':'1. Reader’s Notes','sb':' '},],
		['2. Setting Up OSATE', 'SettingUpOSATE.html',{'tt':'2. Setting Up OSATE','sb':' '},
			['2.1 Get the Components', 'GettheComponents.html',{'tt':'2.1 Get the Components','sb':' '},],
			['2.2 Install Eclipse', 'InstallEclipse.html',{'tt':'2.2 Install Eclipse','sb':' '},],
			['2.3 Verify the Installation', 'VerifytheInstallation.html',{'tt':'2.3 Verify the Installation','sb':' '},],
],
		['3. A First Plug-in: Model Stat... ', 'AFirstPlug-in.ModelStatistics.html',{'tt':'3. A First Plug-in: Model Statistics','sb':' '},
			['3.1 Creating a New Plug-in', 'CreatingaNewPlug-in.html',{'tt':'3.1 Creating a New Plug-in','sb':' '},],
			['3.2 Gathering Model Statistics', 'GatheringModelStatistics.html',{'tt':'3.2 Gathering Model Statistics','sb':' '},],
			['3.3 Driving the Plug-in', 'DrivingthePlug-in.html',{'tt':'3.3 Driving the Plug-in','sb':' '},],
			['3.4 Creating an Icon for the P... ', 'CreatinganIconforthePlug-in.html',{'tt':'3.4 Creating an Icon for the Plug-in','sb':' '},],
			['3.5 Describing the Action in t... ', 'DescribingtheActionintheplugin.xmlFile.html',{'tt':'3.5 Describing the Action in the plugin.xml File','sb':' '},],
			['3.6 Executing the Model Statis... ', 'ExecutingtheModelStatisticsPlug-in.html',{'tt':'3.6 Executing the Model Statistics Plug-in','sb':' '},],
			['3.7 Summary of Concepts', 'SummaryofConcepts.html',{'tt':'3.7 Summary of Concepts','sb':' '},],
],
		['4. Processing of AADL Models', 'ProcessingofAADLModels.html',{'tt':'4. Processing of AADL Models','sb':' '},
			['4.1 Meta Model Defined AADL Mo... ', 'MetaModelDefinedAADLModels.html',{'tt':'4.1 Meta Model Defined AADL Models','sb':' '},],
			['4.2 Notes on Accessing Models', 'NotesonAccessingModels.html',{'tt':'4.2 Notes on Accessing Models','sb':' '},],
			['4.3 AADL Model Traversal Suppo... ', 'AADLModelTraversalSupport.html',{'tt':'4.3 AADL Model Traversal Support','sb':' '},],
			['4.4 AADL Model Manipulation Su... ', 'AADLModelManipulationSupport.html',{'tt':'4.4 AADL Model Manipulation Support','sb':' '},],
],
		['5. Processing AADL Properties', 'ProcessingAADLProperties.html',{'tt':'5. Processing AADL Properties','sb':' '},
			['5.1 The Security Level Plug-in', 'TheSecurityLevelPlug-in.html',{'tt':'5.1 The Security Level Plug-in','sb':' '},],
			['5.2 An Overview of AADL Proper... ', 'AnOverviewofAADLProperties.html',{'tt':'5.2 An Overview of AADL Properties','sb':' '},],
			['5.3 AADL Properties in the Met... ', 'AADLPropertiesintheMetaModel.html',{'tt':'5.3 AADL Properties in the Meta Model','sb':' '},],
			['5.4 Implementing the Security ... ', 'ImplementingtheSecurityLevelPlug-in.html',{'tt':'5.4 Implementing the Security Level Plug-in','sb':' '},],
			['5.5 Getting Simple Property Va... ', 'GettingSimplePropertyValues.html',{'tt':'5.5 Getting Simple Property Values','sb':' '},],
			['5.6 Manipulating Property Valu... ', 'ManipulatingPropertyValues.html',{'tt':'5.6 Manipulating Property Values','sb':' '},],
			['5.7 Advanced Property Associat... ', 'AdvancedPropertyAssociations.html',{'tt':'5.7 Advanced Property Associations','sb':' '},],
			['5.8 OSATE Properties API', 'OSATEPropertiesAPI.html',{'tt':'5.8 OSATE Properties API','sb':' '},],
],
		['6. Working with Flows', 'WorkingwithFlows.html',{'tt':'6. Working with Flows','sb':' '},
			['6.1 Flow Specifications and Fl... ', 'FlowSpecificationsandFlowInstances.html',{'tt':'6.1 Flow Specifications and Flow Instances','sb':' '},],
			['6.2 Flows in the AADL Meta Mod... ', 'FlowsintheAADLMetaModel.html',{'tt':'6.2 Flows in the AADL Meta Model','sb':' '},],
			['6.3 The Flow Analysis Plug-in', 'TheFlowAnalysisPlug-in.html',{'tt':'6.3 The Flow Analysis Plug-in','sb':' '},],
			['6.4 Specification-Based End-To... ', 'Specification-BasedEnd-To-EndFlowAnalysi.html',{'tt':'6.4 Specification-Based End-To-End Flow Analysis','sb':' '},],
			['6.5 Latency Analysis with Inst... ', 'LatencyAnalysiswithInstanceModels.html',{'tt':'6.5 Latency Analysis with Instance Models','sb':' '},],
],
		['7. Managing the Results of an ... ', 'ManagingtheResultsofanOSATEPlug-in.html',{'tt':'7. Managing the Results of an OSATE Plug-in','sb':' '},
			['7.1 Comparison of Result Manag... ', 'ComparisonofResultManagementMechanisms.html',{'tt':'7.1 Comparison of Result Management Mechanisms','sb':' '},],
],
		['8. Persistent Markers with AAD... ', 'PersistentMarkerswithAADLModels.html',{'tt':'8. Persistent Markers with AADL Models','sb':' '},
			['8.1 OSATE Marker Types', 'OSATEMarkerTypes.html',{'tt':'8.1 OSATE Marker Types','sb':' '},],
			['8.2 ErrorReporter', 'ErrorReporter.html',{'tt':'8.2 ErrorReporter','sb':' '},],
			['8.3 Plug-in Actions and Report... ', 'Plug-inActionsandReporting.html',{'tt':'8.3 Plug-in Actions and Reporting','sb':' '},],
			['8.4 User Defined Reporters', 'UserDefinedReporters.html',{'tt':'8.4 User Defined Reporters','sb':' '},],
			['8.5 How to define new Marker t... ', 'HowtodefinenewMarkertypes.html',{'tt':'8.5 How to define new Marker types','sb':' '},],
],
		['9. Packages Provided by the OS... ', 'PackagesProvidedbytheOSATEPlug-ins.html',{'tt':'9. Packages Provided by the OSATE Plug-ins','sb':' '},],

]
];