package org.osate.ge.internal.graphics;

public enum FeatureType {
	ABSTRACT,
	EVENT_PORT,
	DATA_PORT,
	EVENT_DATA_PORT,
	SUBPROGRAM_ACCESS,
	SUBPROGRAM_GROUP_ACCESS,
	DATA_ACCESS,
	BUS_ACCESS,
	FEATURE_GROUP
}
