var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. Introduction', 'Introduction.html',{'tt':'1. Introduction','sb':' '},],
		['2. ARCHITECTURE ANALYSIS &amp; DES... ', 'ARCHITECTUREANALYSIS&DESIGNLANGUAGE(AADL.html',{'tt':'2. ARCHITECTURE ANALYSIS &amp; DESIGN LANGUAGE (AADL) AS5506','sb':' '},
			['2.1 Foreword', 'Foreword.html',{'tt':'2.1 Foreword','sb':' '},],
			['2.2 Information and Feedback', 'InformationandFeedback.html',{'tt':'2.2 Information and Feedback','sb':' '},],
			['2.3 Scope', 'Scope.html',{'tt':'2.3 Scope','sb':' '},],
			['2.4 References', 'References.html',{'tt':'2.4 References','sb':' '},],
],
		['3. Architecture Analysis &amp; Des... ', 'ArchitectureAnalysis&DesignLanguageSumma.html',{'tt':'3. Architecture Analysis &amp; Design Language Summary','sb':' '},],
		['4. Components\, Packages\, and A... ', 'Components\,Packages\,andAnnexes.html',{'tt':'4. Components\, Packages\, and Annexes','sb':' '},
			['4.1 AADL Specifications', 'AADLSpecifications.html',{'tt':'4.1 AADL Specifications','sb':' '},],
			['4.2 Packages', 'Packages.html',{'tt':'4.2 Packages','sb':' '},],
			['4.3 Component Types', 'ComponentTypes.html',{'tt':'4.3 Component Types','sb':' '},],
			['4.4 Component Implementations', 'ComponentImplementations.html',{'tt':'4.4 Component Implementations','sb':' '},],
			['4.5 Subcomponents', 'Subcomponents.html',{'tt':'4.5 Subcomponents','sb':' '},],
			['4.6 Annex Subclauses and Annex... ', 'AnnexSubclausesandAnnexLibraries.html',{'tt':'4.6 Annex Subclauses and Annex Libraries','sb':' '},],
],
		['5. Software Components', 'SoftwareComponents.html',{'tt':'5. Software Components','sb':' '},
			['5.1 Data', 'Data.html',{'tt':'5.1 Data','sb':' '},],
			['5.2 Subprograms and Subprogram... ', 'SubprogramsandSubprogramCalls.html',{'tt':'5.2 Subprograms and Subprogram Calls','sb':' '},],
			['5.3 Threads', 'Threads.html',{'tt':'5.3 Threads','sb':' '},],
			['5.4 Thread Groups', 'ThreadGroups.html',{'tt':'5.4 Thread Groups','sb':' '},],
			['5.5 Processes', 'Processes.html',{'tt':'5.5 Processes','sb':' '},],
			['5.6 Predeclared Runtime Servic... ', 'PredeclaredRuntimeServices.html',{'tt':'5.6 Predeclared Runtime Services','sb':' '},],
],
		['6. Execution Platform Componen... ', 'ExecutionPlatformComponents.html',{'tt':'6. Execution Platform Components','sb':' '},
			['6.1 Processors', 'Processors.html',{'tt':'6.1 Processors','sb':' '},],
			['6.2 Memory', 'Memory.html',{'tt':'6.2 Memory','sb':' '},],
			['6.3 Buses', 'Buses.html',{'tt':'6.3 Buses','sb':' '},],
			['6.4 Devices', 'Devices.html',{'tt':'6.4 Devices','sb':' '},],
],
		['7. System Composition', 'SystemComposition.html',{'tt':'7. System Composition','sb':' '},
			['7.1 Systems', 'Systems.html',{'tt':'7.1 Systems','sb':' '},],
],
		['8. Features and Shared Access', 'FeaturesandSharedAccess.html',{'tt':'8. Features and Shared Access','sb':' '},
			['8.1 Ports', 'Ports.html',{'tt':'8.1 Ports','sb':' '},],
			['8.2 Port Groups and Port Group... ', 'PortGroupsandPortGroupTypes.html',{'tt':'8.2 Port Groups and Port Group Types','sb':' '},],
			['8.3 Subprograms As Features', 'SubprogramsAsFeatures.html',{'tt':'8.3 Subprograms As Features','sb':' '},],
			['8.4 Subprogram Parameters', 'SubprogramParameters.html',{'tt':'8.4 Subprogram Parameters','sb':' '},],
			['8.5 Subcomponent Access', 'SubcomponentAccess.html',{'tt':'8.5 Subcomponent Access','sb':' '},],
],
		['9. Connections and Flows', 'ConnectionsandFlows.html',{'tt':'9. Connections and Flows','sb':' '},
			['9.1 Connections', 'Connections.html',{'tt':'9.1 Connections','sb':' '},],
			['9.2 Flows', 'Flows.html',{'tt':'9.2 Flows','sb':' '},],
],
		['10. Properties', 'Properties.html',{'tt':'10. Properties','sb':' '},
			['10.1 Property Sets', 'PropertySets.html',{'tt':'10.1 Property Sets','sb':' '},],
			['10.2 Predeclared Property Sets', 'PredeclaredPropertySets.html',{'tt':'10.2 Predeclared Property Sets','sb':' '},],
			['10.3 Property Associations', 'PropertyAssociations.html',{'tt':'10.3 Property Associations','sb':' '},],
			['10.4 Property Expressions', 'PropertyExpressions.html',{'tt':'10.4 Property Expressions','sb':' '},],
],
		['11. Operational Modes', 'OperationalModes.html',{'tt':'11. Operational Modes','sb':' '},
			['11.1 Mode', 'Mode.html',{'tt':'11.1 Mode','sb':' '},],
],
		['12. Operational System', 'OperationalSystem.html',{'tt':'12. Operational System','sb':' '},
			['12.1 System Instances', 'SystemInstances.html',{'tt':'12.1 System Instances','sb':' '},],
			['12.2 System Binding', 'SystemBinding.html',{'tt':'12.2 System Binding','sb':' '},],
			['12.3 System Operation', 'SystemOperation.html',{'tt':'12.3 System Operation','sb':' '},],
],
		['13. Lexical Elements', 'LexicalElements.html',{'tt':'13. Lexical Elements','sb':' '},
			['13.1 Character Set', 'CharacterSet.html',{'tt':'13.1 Character Set','sb':' '},],
			['13.2 Lexical Elements\, Separat... ', 'LexicalElements\,Separators\,andDelimiters.html',{'tt':'13.2 Lexical Elements\, Separators\, and Delimiters','sb':' '},],
			['13.3 Identifiers', 'Identifiers.html',{'tt':'13.3 Identifiers','sb':' '},],
			['13.4 Numerical Literals', 'NumericalLiterals.html',{'tt':'13.4 Numerical Literals','sb':' '},],
			['13.5 String Literals', 'StringLiterals.html',{'tt':'13.5 String Literals','sb':' '},],
			['13.6 Comments', 'Comments.html',{'tt':'13.6 Comments','sb':' '},],
			['13.7 Reserved Words', 'ReservedWords.html',{'tt':'13.7 Reserved Words','sb':' '},],
],
		['14. Predeclared Property Sets', 'PredeclaredPropertySets(2).html',{'tt':'14. Predeclared Property Sets','sb':' '},
			['14.1 Standard AADL Property Se... ', 'StandardAADLPropertySet.html',{'tt':'14.1 Standard AADL Property Set','sb':' '},],
			['14.2 Project-Specific Property... ', 'Project-SpecificPropertySet.html',{'tt':'14.2 Project-Specific Property Set','sb':' '},],
],
		['15. Profiles and Extensions', 'ProfilesandExtensions.html',{'tt':'15. Profiles and Extensions','sb':' '},
			['15.1 Allowed Subsets and Restr... ', 'AllowedSubsetsandRestrictions.html',{'tt':'15.1 Allowed Subsets and Restrictions','sb':' '},],
],
		['16. Glossary', 'Glossary.html',{'tt':'16. Glossary','sb':' '},],
		['17. Syntax Summary', 'SyntaxSummary.html',{'tt':'17. Syntax Summary','sb':' '},],
		['18. Graphical AADL Notation', 'GraphicalAADLNotation.html',{'tt':'18. Graphical AADL Notation','sb':' '},
			['18.1 AADL Graphical Symbols', 'AADLGraphicalSymbols.html',{'tt':'18.1 AADL Graphical Symbols','sb':' '},],
			['18.2 System Structure and Topo... ', 'SystemStructureandTopology.html',{'tt':'18.2 System Structure and Topology','sb':' '},],
],
		['19. Unified Modeling Language ... ', 'UnifiedModelingLanguage(UML)Profile.html',{'tt':'19. Unified Modeling Language (UML) Profile','sb':' '},],
		['20. AADL Meta Model &amp; Data Int... ', 'AADLMetaModel&DataInterchangeFormats.html',{'tt':'20. AADL Meta Model &amp; Data Interchange Formats','sb':' '},],
		['21. Language Compliance and Ap... ', 'LanguageComplianceandApplicationProgramI.html',{'tt':'21. Language Compliance and Application Program Interface','sb':' '},
			['21.1 Ada Language Compliance a... ', 'AdaLanguageComplianceandApplicationProgr.html',{'tt':'21.1 Ada Language Compliance and Application Program Interface','sb':' '},],
			['21.2 C Language Compliance and... ', 'CLanguageComplianceandApplicationProgram.html',{'tt':'21.2 C Language Compliance and Application Program Interface','sb':' '},],
],
		['22. Error Model', 'ErrorModel.html',{'tt':'22. Error Model','sb':' '},],
		['23. Possible Tools', 'PossibleTools.html',{'tt':'23. Possible Tools','sb':' '},],

]
];