<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sandbox"
    nsURI="http://www.osate.org/xtext/aadl2/sandbox/Sandbox" nsPrefix="sandbox">
  <eClassifiers xsi:type="ecore:EClass" name="Sandbox">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInstance" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.osate.xtext.aadl2.sandbox/src-gen/org/osate/xtext/aadl2/sandbox/Sandbox.ecore#//SystemConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemImplementation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInstanceProxy" eType="ecore:EClass platform:/resource/org.osate.xtext.aadl2.sandbox/src-gen/org/osate/xtext/aadl2/sandbox/Sandbox.ecore#//SystemInstanceProxy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemInstanceProxy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceRef" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
