<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genmodel"
    nsURI="http://www.eclipse.org/uml2/2.2.0/GenModel" nsPrefix="genmodel">
  <eClassifiers xsi:type="ecore:EClass" name="GenBase" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenClass" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClass #//GenClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenClassifier" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClassifier #//GenBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenDataType" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenDataType #//GenClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenEnum" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenEnum #//GenDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenEnumLiteral" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenEnumLiteral #//GenBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenFeature" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenFeature #//GenTypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluralizationException"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenModel" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenModel #//GenBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryMethods" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluralizedGetters" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheAdapterSupport" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safeStrings" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariantPrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenOperation" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenOperation #//GenTypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheAdapterScope" eType="#//GenCacheAdapterScope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenPackage" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenPackage #//GenBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceInterfaces" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationsPackage" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenParameter" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenParameter #//GenTypedElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="GenCacheAdapterScope">
    <eLiterals name="None"/>
    <eLiterals name="Global" value="1"/>
    <eLiterals name="Resource" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenTypedElement" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenTypedElement #//GenBase"/>
</ecore:EPackage>
