package org.osate.ge.services;

import org.eclipse.xtext.resource.XtextResourceSet;

/**
 * Service for referencing business objects using a string value. Most referenced are handled by the IndependenceProvider(that uses this service)
 * but in some cases, identifiers needs to be generated by other classes.
 * @author philip.alldredge
 *
 */
public interface SerializableReferenceService {
	String getReference(final Object bo);
	Object getReferencedObject(final XtextResourceSet resourceSet, final String reference);
}
