<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modemodel" nsURI="http://osate.org/modemodel" nsPrefix="modemodel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The node representing the initial mode on this level."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SOMNode" abstract="true">
    <eOperations name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="hasMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outTransitions" upperBound="-1"
        eType="#//Transition" transient="true" resolveProxies="false" eOpposite="#//Transition/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inTransitions" upperBound="-1"
        eType="#//Transition" transient="true" resolveProxies="false" eOpposite="#//Transition/dst"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//SOMNode" resolveProxies="false" eOpposite="#//SOMNode/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//SOMNode" transient="true" resolveProxies="false" eOpposite="#//SOMNode/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reachable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mode" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//ModeInstance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The next mode if the component is activated, unset if the component has no modes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//SOMLevel"
        eOpposite="#//SOMLevel/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inactiveConnections" upperBound="-1"
        eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//ConnectionInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inactiveComponents" upperBound="-1"
        eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SOMLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//SOMNode" containment="true" eOpposite="#//SOMNode/level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNode" lowerBound="1"
        eType="#//SOMNode" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InactiveNode" eSuperTypes="#//SOMNode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an inactive component."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveNode" eSuperTypes="#//SOMNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//SOMNode"
        resolveProxies="false" eOpposite="#//SOMNode/outTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" lowerBound="1" eType="#//SOMNode"
        resolveProxies="false" eOpposite="#//SOMNode/inTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//Trigger" resolveProxies="false" eOpposite="#//Trigger/transitions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The trigger must be active such that the transition can occur."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//ConnectionInstance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Connection references identify the connections that must be active such that the transition can occur."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An instance of this class represents the logical origin of an event that causes a mode transition. &#xA;&#xA;All mode transitions that have the same trigger source happen simultaneously [13.6 (1)]&#xA;&#xA;Note: If the same event causes mode transitions in different synchronization domains, there must be different TriggerSource instances for each target synchronization domain."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" transient="true" resolveProxies="false" eOpposite="#//Transition/trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//TriggerKey"
        resolveProxies="false" eOpposite="#//TriggerKey/trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//ComponentInstance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The component in which a trigger originates. The trigger can only occur if this component is active."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SOMGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1"
        eType="#//SOMLevel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//TriggerMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureTrigger" eSuperTypes="#//Trigger">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The trigger originates at a component feature:&#xA;- outgoing feature of a subcomponent&#xA;- incoming feature of the root system (external trigger)&#xA;- outgoing feature of another component in the system"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalFeature" lowerBound="1"
        eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//InternalFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Trigger"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//TriggerKey"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerKey" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//Trigger" resolveProxies="false" eOpposite="#//Trigger/key"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureKey" eSuperTypes="#//TriggerKey">
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalKey" eSuperTypes="#//TriggerKey">
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
