/**
 * generated by Xtext 2.17.0
 */
package org.osate.expr.expr;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comma Separated Expressions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osate.expr.expr.CommaSeparatedExpressions#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.osate.expr.expr.ExprPackage#getCommaSeparatedExpressions()
 * @model
 * @generated
 */
public interface CommaSeparatedExpressions extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.osate.expr.expr.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.osate.expr.expr.ExprPackage#getCommaSeparatedExpressions_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getElements();

} // CommaSeparatedExpressions
