/**
 * generated by Xtext 2.17.0
 */
package org.osate.expr.expr;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.osate.expr.expr.ExprPackage#getSetLiteral()
 * @model
 * @generated
 */
public interface SetLiteral extends Expression
{
} // SetLiteral
