<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EMV2Instance" nsURI="http://www.osate.org/EMV2Instance" nsPrefix="EMV2Instance">
  <eClassifiers xsi:type="ecore:EClass" name="EMV2AnnexInstance" eSuperTypes="../../org.osate.aadl2/model/instance.ecore#//AnnexInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//StateTransitionInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propagationPoints" upperBound="-1"
        eType="#//PropagationPointInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//EventInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//StateMachineInstance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorPropagationConditions"
        upperBound="-1" eType="#//ErrorPropagationConditionInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorDetections" upperBound="-1"
        eType="#//ErrorDetectionInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorFlows" upperBound="-1"
        eType="#//ErrorFlowInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composites" upperBound="-1"
        eType="#//CompositeStateInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propagationPaths" upperBound="-1"
        eType="#//PropagationPathInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMV2InstanceObject" abstract="true"
      eSuperTypes="../../org.osate.aadl2/model/instance.ecore#//InstanceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachineInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//StateInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//StateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="ecore:EClass generated/ErrorModel.ecore#//ErrorBehaviorStateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateInstance" eSuperTypes="#//EMV2InstanceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrainedInstanceObject" eSuperTypes="#//ConstraintElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceObject" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//InstanceObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="ecore:EClass generated/ErrorModel.ecore#//TypeToken" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propagationKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateTransitionInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateTransition" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStates" upperBound="-1"
        eType="#//StateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConstraintElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//StateInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeStateInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//StateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConstraintElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeState" eType="ecore:EClass generated/ErrorModel.ecore#//CompositeState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorFlowInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emv2Element" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//ConstrainedInstanceObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//ConstrainedInstanceObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorPropagationConditionInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emv2Element" eType="ecore:EClass generated/ErrorModel.ecore#//OutgoingPropagationCondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStates" upperBound="-1"
        eType="#//StateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConstraintElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingPropagation" eType="#//ConstrainedInstanceObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorDetectionInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emv2Element" eType="ecore:EClass generated/ErrorModel.ecore#//ErrorDetection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStates" upperBound="-1"
        eType="#//StateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConstraintElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagationPointInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propagationPoint" eType="ecore:EClass generated/ErrorModel.ecore#//PropagationPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass generated/ErrorModel.ecore#//ErrorBehaviorEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedTypedEvents" upperBound="-1"
        eType="#//ConstrainedInstanceObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintExpression" eSuperTypes="#//ConstraintElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintElements" upperBound="-1"
        eType="#//ConstraintElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintElement" abstract="true" eSuperTypes="#//EMV2InstanceObject"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EOperation">
    <eLiterals name="ANY" literal="any"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="ONEOF" value="2" literal="oneof"/>
    <eLiterals name="KOFN" value="3" literal="kofn"/>
    <eLiterals name="KORMORE" value="4" literal="kormore"/>
    <eLiterals name="KORLESS" value="5" literal="korless"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagationPathInstance" eSuperTypes="#//EMV2InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emv2Element" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ConstrainedInstanceObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ConstrainedInstanceObject"/>
  </eClassifiers>
</ecore:EPackage>
