var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. Scope', 'Scope.html',{'tt':'1. Scope','sb':' '},],
		['2. Meta Model Notation', 'MetaModelNotation.html',{'tt':'2. Meta Model Notation','sb':' '},
			['2.1 The Graphical Meta Model N... ', 'TheGraphicalMetaModelNotation.html',{'tt':'2.1 The Graphical Meta Model Notation','sb':' '},],
			['2.2 Mapping to XML Documents', 'MappingtoXMLDocuments.html',{'tt':'2.2 Mapping to XML Documents','sb':' '},],
			['2.3 Validation of the AADL Met... ', 'ValidationoftheAADLMetaModel.html',{'tt':'2.3 Validation of the AADL Meta Model','sb':' '},],
],
		['3. References', 'References.html',{'tt':'3. References','sb':' '},],
		['4. Declarative AADL Model', 'DeclarativeAADLModel.html',{'tt':'4. Declarative AADL Model','sb':' '},
			['4.1 Modular Meta Model', 'ModularMetaModel.html',{'tt':'4.1 Modular Meta Model','sb':' '},],
			['4.2 Hierarchy of Abstract and ... ', 'HierarchyofAbstractandConcreteClasses.html',{'tt':'4.2 Hierarchy of Abstract and Concrete Classes','sb':' '},],
			['4.3 Component Types\, Implement... ', 'ComponentTypes\,Implementations\,andSubcom.html',{'tt':'4.3 Component Types\, Implementations\, and Subcomponents','sb':' '},],
			['4.4 Category-Specific Meta Mod... ', 'Category-SpecificMetaModelClasses.html',{'tt':'4.4 Category-Specific Meta Model Classes','sb':' '},],
			['4.5 Component Extension and Re... ', 'ComponentExtensionandRefinement.html',{'tt':'4.5 Component Extension and Refinement','sb':' '},],
			['4.6 Category-Specific Containm... ', 'Category-SpecificContainmentandOrdering.html',{'tt':'4.6 Category-Specific Containment and Ordering','sb':' '},],
			['4.7 Features', 'Features.html',{'tt':'4.7 Features','sb':' '},],
			['4.8 Port Group Types', 'PortGroupTypes.html',{'tt':'4.8 Port Group Types','sb':' '},],
			['4.9 Connections', 'Connections.html',{'tt':'4.9 Connections','sb':' '},],
			['4.10 Flows', 'Flows.html',{'tt':'4.10 Flows','sb':' '},],
			['4.11 Call Sequences', 'CallSequences.html',{'tt':'4.11 Call Sequences','sb':' '},],
			['4.12 Modes and Mode Transition... ', 'ModesandModeTransitions.html',{'tt':'4.12 Modes and Mode Transitions','sb':' '},],
			['4.13 Property Associations', 'PropertyAssociations.html',{'tt':'4.13 Property Associations','sb':' '},],
			['4.14 Property Values', 'PropertyValues.html',{'tt':'4.14 Property Values','sb':' '},],
			['4.15 AADL Packages', 'AADLPackages.html',{'tt':'4.15 AADL Packages','sb':' '},],
			['4.16 Property Sets\, Types\, Con... ', 'PropertySets\,Types\,Constants\,andDefiniti.html',{'tt':'4.16 Property Sets\, Types\, Constants\, and Definitions','sb':' '},],
			['4.17 Annex Libraries and Annex... ', 'AnnexLibrariesandAnnexSubclauses.html',{'tt':'4.17 Annex Libraries and Annex Subclauses','sb':' '},],
],
		['5. AADL Instance Model', 'AADLInstanceModel.html',{'tt':'5. AADL Instance Model','sb':' '},],
		['6. Graphical Layout Model', 'GraphicalLayoutModel.html',{'tt':'6. Graphical Layout Model','sb':' '},],
		['7. The AADL Meta Model in Ecor... ', 'TheAADLMetaModelinEcore.html',{'tt':'7. The AADL Meta Model in Ecore','sb':' '},
			['7.1 The Core Package of the AA... ', 'TheCorePackageoftheAADLMetaModel.html',{'tt':'7.1 The Core Package of the AADL Meta Model','sb':' '},],
			['7.2 The Component Package of t... ', 'TheComponentPackageoftheAADLMetaModel.html',{'tt':'7.2 The Component Package of the AADL Meta Model','sb':' '},],
			['7.3 The Connection Package of ... ', 'TheConnectionPackageoftheAADLMetaModel.html',{'tt':'7.3 The Connection Package of the AADL Meta Model','sb':' '},],
			['7.4 The Feature Package of the... ', 'TheFeaturePackageoftheAADLMetaModel.html',{'tt':'7.4 The Feature Package of the AADL Meta Model','sb':' '},],
			['7.5 The Flow Package of the AA... ', 'TheFlowPackageoftheAADLMetaModel.html',{'tt':'7.5 The Flow Package of the AADL Meta Model','sb':' '},],
			['7.6 The Property Package of th... ', 'ThePropertyPackageoftheAADLMetaModel.html',{'tt':'7.6 The Property Package of the AADL Meta Model','sb':' '},],
			['7.7 The Instance Package of th... ', 'TheInstancePackageoftheAADLMetaModel.html',{'tt':'7.7 The Instance Package of the AADL Meta Model','sb':' '},],
],
		['8. The XMI Specification for A... ', 'TheXMISpecificationforAADL.html',{'tt':'8. The XMI Specification for AADL','sb':' '},
			['8.1 The Core XMI Specification... ', 'TheCoreXMISpecificationoftheAADLMetaMode.html',{'tt':'8.1 The Core XMI Specification of the AADL Meta Model','sb':' '},],
			['8.2 The Component XMI Specific... ', 'TheComponentXMISpecificationoftheAADLMet.html',{'tt':'8.2 The Component XMI Specification of the AADL Meta Model','sb':' '},],
			['8.3 The Connection XMI Specifi... ', 'TheConnectionXMISpecificationoftheAADLMe.html',{'tt':'8.3 The Connection XMI Specification of the AADL Meta Model','sb':' '},],
			['8.4 The Feature XMI Specificat... ', 'TheFeatureXMISpecificationoftheAADLMetaM.html',{'tt':'8.4 The Feature XMI Specification of the AADL Meta Model','sb':' '},],
			['8.5 The Flow XMI Specification... ', 'TheFlowXMISpecificationoftheAADLMetaMode.html',{'tt':'8.5 The Flow XMI Specification of the AADL Meta Model','sb':' '},],
			['8.6 The Property XMI Specifica... ', 'ThePropertyXMISpecificationoftheAADLMeta.html',{'tt':'8.6 The Property XMI Specification of the AADL Meta Model','sb':' '},],
			['8.7 The Instance XMI Specifica... ', 'TheInstanceXMISpecificationoftheAADLMeta.html',{'tt':'8.7 The Instance XMI Specification of the AADL Meta Model','sb':' '},],
			['8.8 The XMI.xsd Specification', 'TheXMI.xsdSpecification.html',{'tt':'8.8 The XMI.xsd Specification','sb':' '},],
],
		['9. The XML Schema Specificatio... ', 'TheXMLSchemaSpecificationforAADL.html',{'tt':'9. The XML Schema Specification for AADL','sb':' '},
			['9.1 The Core XML Schema of the... ', 'TheCoreXMLSchemaoftheAADLMetaModel.html',{'tt':'9.1 The Core XML Schema of the AADL Meta Model','sb':' '},],
			['9.2 The Component XML Schema o... ', 'TheComponentXMLSchemaoftheAADLMetaModel.html',{'tt':'9.2 The Component XML Schema of the AADL Meta Model','sb':' '},],
			['9.3 The Connection XML Schema ... ', 'TheConnectionXMLSchemaoftheAADLMetaModel.html',{'tt':'9.3 The Connection XML Schema of the AADL Meta Model','sb':' '},],
			['9.4 The Feature XML Schema of ... ', 'TheFeatureXMLSchemaoftheAADLMetaModel.html',{'tt':'9.4 The Feature XML Schema of the AADL Meta Model','sb':' '},],
			['9.5 The Flow XML Schema of the... ', 'TheFlowXMLSchemaoftheAADLMetaModel.html',{'tt':'9.5 The Flow XML Schema of the AADL Meta Model','sb':' '},],
			['9.6 The Property Package of th... ', 'ThePropertyPackageoftheAADLMetaModel(2).html',{'tt':'9.6 The Property Package of the AADL Meta Model','sb':' '},],
			['9.7 The Instance XML Schema of... ', 'TheInstanceXMLSchemaoftheAADLMetaModel.html',{'tt':'9.7 The Instance XML Schema of the AADL Meta Model','sb':' '},],
],

]
];