pluginName = AADL Behavior Annex Xtext Edit
providerName = CMU/SEI
_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.
_UI_PropertyDescriptor_description = The {0} of the {1}
_UI_BehaviorAnnex_type = Behavior Annex
_UI_BehaviorVariableGroup_type = Behavior Variable Group
_UI_BehaviorVariable_type = Behavior Variable
_UI_ArrayDimension_type = Array Dimension
_UI_BehaviorPropertyAssociation_type = Behavior Property Association
_UI_BehaviorStateGroup_type = Behavior State Group
_UI_BehaviorState_type = Behavior State
_UI_BehaviorTransition_type = Behavior Transition
_UI_BehaviorCondition_type = Behavior Condition
_UI_ExecuteCondition_type = Execute Condition
_UI_DispatchCondition_type = Dispatch Condition
_UI_DispatchTriggerCondition_type = Dispatch Trigger Condition
_UI_DispatchTriggerLogicalExpression_type = Dispatch Trigger Logical Expression
_UI_DispatchConjunction_type = Dispatch Conjunction
_UI_ModeSwitchCondition_type = Mode Switch Condition
_UI_ModeSwitchConjunction_type = Mode Switch Conjunction
_UI_BehaviorActionBlock_type = Behavior Action Block
_UI_BehaviorActions_type = Behavior Actions
_UI_BehaviorAction_type = Behavior Action
_UI_AssignmentAction_type = Assignment Action
_UI_CommunicationAction_type = Communication Action
_UI_TimedAction_type = Timed Action
_UI_IfStatement_type = If Statement
_UI_ElseIfClause_type = Else If Clause
_UI_ForStatement_type = For Statement
_UI_WhileStatement_type = While Statement
_UI_DoUntilStatement_type = Do Until Statement
_UI_ElementValues_type = Element Values
_UI_BehaviorTime_type = Behavior Time
_UI_IntegerValue_type = Integer Value
_UI_ValueExpression_type = Value Expression
_UI_ValueConstant_type = Value Constant
_UI_IntegerLiteral_type = Integer Literal
_UI_RealLiteral_type = Real Literal
_UI_StringLiteral_type = String Literal
_UI_BooleanLiteral_type = Boolean Literal
_UI_ReferenceExpression_type = Reference Expression
_UI_HashPropertyReference_type = Hash Property Reference
_UI_PropertyReferenceTail_type = Property Reference Tail
_UI_PropertyField_type = Property Field
_UI_Reference_type = Reference
_UI_ReferenceTail_type = Reference Tail
_UI_ReferenceSegment_type = Reference Segment
_UI_ArrayIndex_type = Array Index
_UI_BehaviorActionSequence_type = Behavior Action Sequence
_UI_BehaviorActionSet_type = Behavior Action Set
_UI_BinaryExpression_type = Binary Expression
_UI_UnaryExpression_type = Unary Expression
_UI_Unknown_type = Object
_UI_Unknown_datatype= Value
_UI_BehaviorAnnex_variableGroups_feature = Variable Groups
_UI_BehaviorAnnex_stateGroups_feature = State Groups
_UI_BehaviorAnnex_transitions_feature = Transitions
_UI_BehaviorVariableGroup_variables_feature = Variables
_UI_BehaviorVariableGroup_dataClassifier_feature = Data Classifier
_UI_BehaviorVariableGroup_initialValue_feature = Initial Value
_UI_BehaviorVariableGroup_propertyAssociations_feature = Property Associations
_UI_BehaviorVariable_name_feature = Name
_UI_BehaviorVariable_arrayDimensions_feature = Array Dimensions
_UI_ArrayDimension_size_feature = Size
_UI_BehaviorPropertyAssociation_property_feature = Property
_UI_BehaviorPropertyAssociation_ownedValue_feature = Owned Value
_UI_BehaviorStateGroup_states_feature = States
_UI_BehaviorStateGroup_initial_feature = Initial
_UI_BehaviorStateGroup_complete_feature = Complete
_UI_BehaviorStateGroup_final_feature = Final
_UI_BehaviorState_name_feature = Name
_UI_BehaviorTransition_name_feature = Name
_UI_BehaviorTransition_priority_feature = Priority
_UI_BehaviorTransition_sourceStates_feature = Source States
_UI_BehaviorTransition_condition_feature = Condition
_UI_BehaviorTransition_destinationState_feature = Destination State
_UI_BehaviorTransition_actionBlock_feature = Action Block
_UI_BehaviorCondition_dispatch_feature = Dispatch
_UI_BehaviorCondition_modeSwitch_feature = Mode Switch
_UI_BehaviorCondition_execute_feature = Execute
_UI_ExecuteCondition_value_feature = Value
_UI_ExecuteCondition_timeout_feature = Timeout
_UI_ExecuteCondition_otherwise_feature = Otherwise
_UI_DispatchCondition_trigger_feature = Trigger
_UI_DispatchCondition_frozenPorts_feature = Frozen Ports
_UI_DispatchTriggerCondition_expression_feature = Expression
_UI_DispatchTriggerCondition_timeout_feature = Timeout
_UI_DispatchTriggerCondition_time_feature = Time
_UI_DispatchTriggerCondition_stop_feature = Stop
_UI_DispatchTriggerLogicalExpression_conjunctions_feature = Conjunctions
_UI_DispatchConjunction_triggers_feature = Triggers
_UI_ModeSwitchCondition_conjunctions_feature = Conjunctions
_UI_ModeSwitchConjunction_triggers_feature = Triggers
_UI_BehaviorActionBlock_content_feature = Content
_UI_BehaviorActionBlock_timeout_feature = Timeout
_UI_AssignmentAction_target_feature = Target
_UI_AssignmentAction_value_feature = Value
_UI_AssignmentAction_any_feature = Any
_UI_CommunicationAction_reference_feature = Reference
_UI_CommunicationAction_send_feature = Send
_UI_CommunicationAction_parameters_feature = Parameters
_UI_CommunicationAction_dequeue_feature = Dequeue
_UI_CommunicationAction_target_feature = Target
_UI_CommunicationAction_freeze_feature = Freeze
_UI_CommunicationAction_lock_feature = Lock
_UI_CommunicationAction_unlock_feature = Unlock
_UI_CommunicationAction_all_feature = All
_UI_CommunicationAction_allLock_feature = All Lock
_UI_CommunicationAction_allUnlock_feature = All Unlock
_UI_TimedAction_lowerTime_feature = Lower Time
_UI_TimedAction_upperTime_feature = Upper Time
_UI_TimedAction_processors_feature = Processors
_UI_IfStatement_condition_feature = Condition
_UI_IfStatement_thenActions_feature = Then Actions
_UI_IfStatement_elseIfs_feature = Else Ifs
_UI_IfStatement_elseActions_feature = Else Actions
_UI_ElseIfClause_condition_feature = Condition
_UI_ElseIfClause_actions_feature = Actions
_UI_ForStatement_for_feature = For
_UI_ForStatement_forall_feature = Forall
_UI_ForStatement_variable_feature = Variable
_UI_ForStatement_dataClassifier_feature = Data Classifier
_UI_ForStatement_values_feature = Values
_UI_ForStatement_actions_feature = Actions
_UI_WhileStatement_condition_feature = Condition
_UI_WhileStatement_actions_feature = Actions
_UI_DoUntilStatement_actions_feature = Actions
_UI_DoUntilStatement_condition_feature = Condition
_UI_ElementValues_lower_feature = Lower
_UI_ElementValues_upper_feature = Upper
_UI_BehaviorTime_value_feature = Value
_UI_BehaviorTime_unit_feature = Unit
_UI_IntegerLiteral_value_feature = Value
_UI_RealLiteral_value_feature = Value
_UI_StringLiteral_value_feature = Value
_UI_ReferenceExpression_reference_feature = Reference
_UI_ReferenceExpression_property_feature = Property
_UI_ReferenceExpression_dequeue_feature = Dequeue
_UI_ReferenceExpression_count_feature = Count
_UI_ReferenceExpression_fresh_feature = Fresh
_UI_HashPropertyReference_property_feature = Property
_UI_HashPropertyReference_fields_feature = Fields
_UI_PropertyReferenceTail_property_feature = Property
_UI_PropertyReferenceTail_fields_feature = Fields
_UI_PropertyField_name_feature = Name
_UI_PropertyField_indexes_feature = Indexes
_UI_Reference_segments_feature = Segments
_UI_Reference_tails_feature = Tails
_UI_ReferenceTail_separator_feature = Separator
_UI_ReferenceTail_segment_feature = Segment
_UI_ReferenceSegment_name_feature = Name
_UI_ReferenceSegment_indexes_feature = Indexes
_UI_ArrayIndex_value_feature = Value
_UI_BehaviorActionSequence_actions_feature = Actions
_UI_BehaviorActionSet_actions_feature = Actions
_UI_BinaryExpression_left_feature = Left
_UI_BinaryExpression_operator_feature = Operator
_UI_BinaryExpression_right_feature = Right
_UI_UnaryExpression_operator_feature = Operator
_UI_UnaryExpression_operand_feature = Operand
_UI_Unknown_feature = Unspecified
_UI_NamedPropertyField_type = Named Property Field
_UI_IndexedPropertyField_type = Indexed Property Field
_UI_NamedPropertyField_name_feature = Name
_UI_PropertyArrayIndex_type = Property Array Index
_UI_PropertyIndexValue_type = Property Index Value
_UI_PropertyIndexPropertyReference_type = Property Index Property Reference
_UI_UnindexedReferenceExpression_type = Unindexed Reference Expression
_UI_UnindexedReference_type = Unindexed Reference
_UI_UnindexedReferenceTail_type = Unindexed Reference Tail
_UI_UnindexedReferenceSegment_type = Unindexed Reference Segment
_UI_PropertyArrayIndex_value_feature = Value
_UI_PropertyIndexPropertyReference_property_feature = Property
_UI_UnindexedReferenceExpression_reference_feature = Reference
_UI_UnindexedReferenceExpression_dequeue_feature = Dequeue
_UI_UnindexedReferenceExpression_count_feature = Count
_UI_UnindexedReferenceExpression_fresh_feature = Fresh
_UI_UnindexedReference_segments_feature = Segments
_UI_UnindexedReference_tails_feature = Tails
_UI_UnindexedReferenceTail_separator_feature = Separator
_UI_UnindexedReferenceTail_segment_feature = Segment
_UI_UnindexedReferenceSegment_name_feature = Name
_UI_BehaviorIntegerLiteral_type = Behavior Integer Literal
_UI_BehaviorRealLiteral_type = Behavior Real Literal
_UI_BehaviorStringLiteral_type = Behavior String Literal
_UI_BehaviorBooleanLiteral_type = Behavior Boolean Literal
_UI_BehaviorIntegerLiteral_value_feature = Value
_UI_BehaviorRealLiteral_value_feature = Value
_UI_BehaviorStringLiteral_value_feature = Value
_UI_BehaviorBooleanLiteral_value_feature = Value
_UI_HashPropertyReference_indexes_feature = Indexes
_UI_PropertyReferenceTail_indexes_feature = Indexes
_UI_NamedPropertyField_indexes_feature = Indexes
