/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.instance;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class InstanceStandaloneSetup extends InstanceStandaloneSetupGenerated{

	public static void doSetup() {
		new InstanceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

