/*
 * generated by Xtext
 */
package org.osate.aadl2.instance.textual;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.serializer.tokens.ICrossReferenceSerializer;
import org.osate.aadl2.instance.textual.linking.InstanceLinkingService;
import org.osate.aadl2.instance.textual.naming.InstanceQualifiedNameConverter;
import org.osate.aadl2.instance.textual.serializer.InstanceCrossReferenceSerializer;
import org.osate.xtext.aadl2.properties.valueconversion.PropertiesValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("restriction")
public class InstanceRuntimeModule extends AbstractInstanceRuntimeModule {
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return InstanceQualifiedNameConverter.class;
	}
	
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return PropertiesValueConverter.class;
	}
	
	public Class<? extends ICrossReferenceSerializer> bindICrossReferenceSerializer() {
		return InstanceCrossReferenceSerializer.class;
	}
	
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return InstanceLinkingService.class;
	}
}