/*
 * generated by Xtext
 */
package org.osate.expr;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExprUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return org.osate.expr.ui.internal.ExprActivator.getInstance().getInjector("org.osate.expr.Expr");
	}

}
