package org.osate.ge.internal.diagram;

public enum DiagramElementField {
	GRAPHIC,
	POSITION,
	SIZE,
	DOCK_AREA,
	LABEL_CONFIGURATION,
	CONNECTION_START,
	CONNECTION_END,
	BENDPOINTS,
	CONNECTION_NAME_LABEL_POSITION
}