/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.ui.outline;

import org.eclipse.core.runtime.NullProgressMonitor;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.osate.aadl2.AadlPackage;
import org.osate.aadl2.Element;
import org.osate.aadl2.ModelUnit;
import org.osate.aadl2.instance.SystemInstance;
import org.osate.aadl2.instantiation.InstantiateModel;
import org.osate.aadl2.modelsupport.AadlConstants;
import org.osate.aadl2.modelsupport.errorreporting.AnalysisErrorReporterManager;
import org.osate.aadl2.modelsupport.errorreporting.InternalErrorReporter;
import org.osate.aadl2.modelsupport.errorreporting.LogInternalErrorReporter;
import org.osate.aadl2.modelsupport.errorreporting.MarkerAnalysisErrorReporter;
import org.osate.core.OsateCorePlugin;

/**
 * customization of the default outline structure
 * 
 */
public class Aadl2OutlineTreeProvider extends DefaultOutlineTreeProvider {

	protected void _createChildren(DocumentRootNode parentNode,	ModelUnit aadlModel) {
		if (aadlModel instanceof AadlPackage) {
			for (Element element : aadlModel.getChildren()) {
				createNode(parentNode, element);
			}
		} else {
			createNode(parentNode, aadlModel);
		}
	}
	
	protected void _createChildren(DocumentRootNode parentNode, SystemInstance aadlModel) {
		createNode(parentNode, aadlModel);
	}
	protected boolean _isLeaf(SystemInstance feature) {
	    return false;
	}
	

	protected static final InternalErrorReporter internalErrorLogger = new LogInternalErrorReporter(OsateCorePlugin
			.getDefault().getBundle());

	protected void _createChildren(IOutlineNode parentNode, SystemInstance aadlModel) {
		if (aadlModel.eContents().isEmpty()){
			final InstantiateModel instantiateModel =
			new InstantiateModel(new NullProgressMonitor(),
					new AnalysisErrorReporterManager(
							internalErrorLogger,
							new MarkerAnalysisErrorReporter.Factory(
									AadlConstants.INSTANTIATION_OBJECT_MARKER)));
			instantiateModel.createXSystemInstance(aadlModel);
		}
		super._createChildren(parentNode, aadlModel);
	}

	// Uncomment the next set to limit outline for package and property set to 

//	// Classifier nodes are leafs and not expandable
//	protected boolean _isLeaf(Classifier feature) {
//	    return true;
//	}
//
//	// Property nodes are leafs and not expandable
//	protected boolean _isLeaf(Property feature) {
//	    return true;
//	}
//
//	// PropertyConstant nodes are leafs and not expandable
//	protected boolean _isLeaf(PropertyConstant feature) {
//	    return true;
//	}
//
//	// PropertyType nodes are leafs and not expandable
//	protected boolean _isLeaf(PropertyType feature) {
//	    return true;
//	}

	

}
