<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagram" nsURI="http://osate.org/diagram" nsPrefix="diagram">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//DiagramNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//DiagramConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//DiagramElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramElement" eSuperTypes="#//DiagramNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//LongObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bo" eType="#//RelativeBusinessObjectReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manual" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoContentsFilter" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Point"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Dimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dockArea" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" eType="#//BendpointList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryLabelPosition" eType="#//Point"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Only supported for connections."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outline" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontColor" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryLabelVisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BendpointList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="point" upperBound="-1"
        eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AadlPropertiesSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CanonicalBusinessObjectReference" eSuperTypes="#//Reference"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeBusinessObjectReference" eSuperTypes="#//Reference"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledAadlProperties"
        eType="#//AadlPropertiesSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//CanonicalBusinessObjectReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionPrimaryLabelsVisible"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seg" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Color" instanceClassName="java.lang.String"/>
</ecore:EPackage>
